spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: admin
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: reservation-service
      bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
    producer:
      useNativeEncoding: true
      bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
application:
  security:
    jwt:
      secret-key: 2ADDFD5C436226A765CHSADFDAS33212332138A3BE26A
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org.apache.kafka: ERROR
    org.apache.kafka.clients: ERROR
    org.springframework.kafka: ERROR
    kafka: ERROR